# Generated by Django 4.2.4 on 2023-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=15)),
                ('productDescription', models.TextField()),
                ('productPrice', models.IntegerField()),
                ('productImage', models.ImageField(default='null.jpg', upload_to='PRODUCT_IMAGE')),
            ],
        ),
    ]
