# Generated by Django 4.2.4 on 2023-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='null.jpg', max_length=100),
        ),
    ]
