# Generated by Django 4.2.4 on 2023-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINAPP', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
