# Generated by Django 4.2.4 on 2023-09-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINAPP', '0005_product_category'),
        ('USERAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='City',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='State',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='USERAPP.register'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='productPrice',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='')),
                ('total', models.IntegerField(default='')),
                ('status', models.IntegerField(default=0)),
                ('productid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ADMINAPP.product')),
                ('userid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='USERAPP.register')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cartid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='USERAPP.cart'),
        ),
    ]
