# Generated by Django 4.2.4 on 2023-09-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINAPP', '0005_product_category'),
        ('USERAPP', '0002_booking_address_booking_city_booking_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cartid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.cart'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.register'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMINAPP.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.register'),
        ),
    ]
