# Generated by Django 4.2.4 on 2023-09-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0006_alter_cart_quantity_alter_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Phone_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='productPrice',
        ),
    ]
