# Generated by Django 4.2.5 on 2023-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0008_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
