# Generated by Django 4.2.5 on 2023-09-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINAPP', '0005_product_category'),
        ('USERAPP', '0009_booking_status_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=255)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMINAPP.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERAPP.register')),
            ],
        ),
    ]
