# Generated by Django 4.2.5 on 2023-09-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0010_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cartid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='USERAPP.cart'),
        ),
    ]
